export const BIOMES = {
  "meadow-edge": {
    id: "meadow-edge",
    name: "Meadow's Edge",
    baseColor: "#2a6b3a",
    accentColor: "#4a9e58",
    pathColor: "#c4a86a",
    pathEdgeColor: "#8b7348",
    noiseTint: "rgba(120,200,90,0.12)",
    waterColor: null,
  },
  "stump-crossroads": {
    id: "stump-crossroads",
    name: "Old Stump Crossroads",
    baseColor: "#3d4a32",
    accentColor: "#5c6b48",
    pathColor: "#b89a6e",
    pathEdgeColor: "#7a6544",
    noiseTint: "rgba(90,70,50,0.15)",
    waterColor: null,
  },
  "whispering-river": {
    id: "whispering-river",
    name: "Whispering River",
    baseColor: "#1e5a4a",
    accentColor: "#3a8a72",
    pathColor: "#c9b080",
    pathEdgeColor: "#8a7550",
    noiseTint: "rgba(60,140,120,0.14)",
    waterColor: "rgba(40,120,160,0.55)",
  },
  "mushroom-hollow": {
    id: "mushroom-hollow",
    name: "Mushroom Hollow",
    baseColor: "#1a2838",
    accentColor: "#6a4a9a",
    pathColor: "#8a7a68",
    pathEdgeColor: "#5a4a3a",
    noiseTint: "rgba(120,80,200,0.18)",
    waterColor: null,
    grassMaterial: "material-mushroom-floor",
    darkness: true,
  },
  sawmill: {
    id: "sawmill",
    name: "Sawmill Clearing",
    baseColor: "#3a3428",
    accentColor: "#8a6a48",
    pathColor: "#9a8870",
    pathEdgeColor: "#6a5a44",
    noiseTint: "rgba(140,100,60,0.16)",
    waterColor: null,
    grassMaterial: "material-sawmill-floor",
  },
  "ashfall-scar": {
    id: "ashfall-scar",
    name: "Ashfall Scar",
    baseColor: "#2a2420",
    accentColor: "#6a5040",
    pathColor: "#8a7868",
    pathEdgeColor: "#5a4a3a",
    noiseTint: "rgba(180,80,40,0.14)",
    waterColor: null,
    grassMaterial: "material-ashfall-floor",
  },
  "boulder-pass": {
    id: "boulder-pass",
    name: "Boulder Pass",
    baseColor: "#3a3830",
    accentColor: "#6a6458",
    pathColor: "#a09078",
    pathEdgeColor: "#6a5e4a",
    noiseTint: "rgba(120,110,90,0.16)",
    waterColor: null,
    grassMaterial: "material-boulder-floor",
  },
};

export function getBiome(id) {
  return BIOMES[id] || BIOMES["meadow-edge"];
}
