export const DEFENDERS = {
  "sprig-sentinel": {
    id: "sprig-sentinel",
    name: "Sprig Sentinel",
    cost: 50,
    range: 160,
    damage: 35,
    cooldown: 1.15,
    hp: 95,
    tags: ["forest", "dps"],
    placement: "beside-path",
    sprite: "sprig-sentinel-idle",
    projectile: "seed-bolt",
  },
  "thornvine-bramble": {
    id: "thornvine-bramble",
    name: "Thornvine Bramble",
    cost: 35,
    range: 0,
    damage: 0,
    cooldown: 0,
    hp: 180,
    tags: ["forest", "blocker"],
    placement: "on-path",
    sprite: "thornvine-bramble-idle",
    blocksPath: true,
  },
  "wisp-willow": {
    id: "wisp-willow",
    name: "Wisp Willow",
    cost: 90,
    range: 180,
    damage: 28,
    cooldown: 0.85,
    hp: 70,
    tags: ["arcane", "anti-air", "chain"],
    placement: "beside-path",
    sprite: "wisp-willow-idle",
    projectile: "chain-lightning",
  },
  "dewdrop-nymph": {
    id: "dewdrop-nymph",
    name: "Dewdrop Nymph",
    cost: 75,
    range: 140,
    damage: 18,
    cooldown: 1.4,
    hp: 80,
    tags: ["control", "slow", "rust", "douses-fire"],
    placement: "beside-path",
    sprite: "dewdrop-nymph-idle",
    projectile: "dew-splash",
  },
  "firefly-beacon": {
    id: "firefly-beacon",
    name: "Firefly Beacon",
    cost: 60,
    range: 0,
    damage: 0,
    cooldown: 0,
    hp: 65,
    tags: ["support", "light"],
    placement: "beside-path",
    sprite: "firefly-beacon-idle",
    glowRadius: 210,
    supportOnly: true,
  },
  "mushroom-shaman": {
    id: "mushroom-shaman",
    name: "Mushroom Shaman",
    cost: 80,
    range: 130,
    damage: 8,
    cooldown: 1.1,
    hp: 85,
    tags: ["poison", "aoe"],
    placement: "beside-path",
    sprite: "mushroom-shaman-idle",
    projectile: "spore-cloud",
    poisonDps: 10,
    poisonDuration: 4,
  },
  "mossback-golem": {
    id: "mossback-golem",
    name: "Mossback Golem",
    cost: 100,
    range: 115,
    damage: 46,
    cooldown: 1.35,
    hp: 290,
    tags: ["forest", "heavy", "armor-pierce"],
    placement: "beside-path",
    sprite: "mossback-golem-idle",
    projectile: "stone-fist",
    armorPierce: 3,
  },
};

export function getDefender(id) {
  return DEFENDERS[id] || null;
}
