export const ENEMIES = {
  logger: {
    id: "logger",
    name: "Logger",
    threatCost: 12,
    hp: 115,
    speed: 42,
    damage: 28,
    attackInterval: 0.95,
    manaBounty: 8,
    tags: ["crew", "ground", "choppable"],
    sprite: "logger-idle",
    width: 54,
    height: 68,
  },
  surveyor: {
    id: "surveyor",
    name: "Surveyor",
    threatCost: 14,
    hp: 95,
    speed: 48,
    damage: 18,
    attackInterval: 1.1,
    manaBounty: 10,
    tags: ["crew", "ground", "marks-targets"],
    sprite: "surveyor-idle",
    width: 50,
    height: 64,
  },
  "chainsaw-brute": {
    id: "chainsaw-brute",
    name: "Chainsaw Brute",
    threatCost: 22,
    hp: 200,
    speed: 30,
    damage: 45,
    attackInterval: 0.8,
    manaBounty: 14,
    tags: ["crew", "ground", "choppable", "heavy-chop"],
    sprite: "chainsaw-brute-idle",
    width: 62,
    height: 72,
  },
  bulldozer: {
    id: "bulldozer",
    name: "Bulldozer",
    threatCost: 28,
    hp: 260,
    speed: 24,
    damage: 52,
    attackInterval: 0.75,
    manaBounty: 15,
    tags: ["machine", "ground", "armored"],
    armor: 1,
    sprite: "bulldozer-idle",
    width: 78,
    height: 58,
  },
  "buzzsaw-drone": {
    id: "buzzsaw-drone",
    name: "Buzzsaw Drone",
    threatCost: 18,
    hp: 85,
    speed: 55,
    damage: 22,
    attackInterval: 1.0,
    manaBounty: 12,
    tags: ["machine", "flying"],
    flying: true,
    sprite: "buzzsaw-drone-idle",
    width: 48,
    height: 48,
  },
  poacher: {
    id: "poacher",
    name: "Poacher",
    threatCost: 16,
    hp: 90,
    speed: 52,
    damage: 20,
    attackInterval: 1.0,
    manaBounty: 11,
    tags: ["crew", "ground", "cloaked", "steals-flowers"],
    cloaked: true,
    ignoresBlockers: true,
    sprite: "poacher-idle",
    width: 52,
    height: 66,
  },
  "the-grinder": {
    id: "the-grinder",
    name: "The Grinder",
    threatCost: 0,
    hp: 1180,
    speed: 22,
    damage: 62,
    attackInterval: 0.72,
    manaBounty: 55,
    tags: ["machine", "ground", "boss"],
    boss: true,
    sprite: "the-grinder-idle",
    damagedSprite: "the-grinder-damaged",
    width: 96,
    height: 80,
  },
  arsonist: {
    id: "arsonist",
    name: "Arsonist",
    threatCost: 18,
    hp: 105,
    speed: 46,
    damage: 22,
    attackInterval: 1.0,
    manaBounty: 12,
    tags: ["crew", "ground", "ignites-rings"],
    sprite: "arsonist-idle",
    width: 54,
    height: 66,
  },
  "diesel-hauler": {
    id: "diesel-hauler",
    name: "Diesel Hauler",
    threatCost: 20,
    hp: 210,
    speed: 26,
    damage: 38,
    attackInterval: 0.85,
    manaBounty: 16,
    tags: ["machine", "ground", "smoke-aura"],
    armor: 1,
    smokeAura: { radius: 180, rangeReduction: 0.32 },
    sprite: "diesel-hauler-idle",
    width: 72,
    height: 58,
  },
  "tunnel-borer": {
    id: "tunnel-borer",
    name: "Tunnel Borer",
    threatCost: 16,
    hp: 100,
    speed: 50,
    damage: 25,
    attackInterval: 1.0,
    manaBounty: 12,
    tags: ["machine", "ground", "burrows"],
    burrow: { duration: 3, jumpDistance: 380, cooldown: 3.5 },
    sprite: "tunnel-borer-idle",
    width: 58,
    height: 52,
  },
  excavator: {
    id: "excavator",
    name: "Excavator",
    threatCost: 0,
    hp: 1150,
    speed: 22,
    damage: 55,
    attackInterval: 0.83,
    manaBounty: 42,
    tags: ["machine", "ground", "mini-boss"],
    armor: 3,
    sprite: "excavator-idle",
    width: 88,
    height: 72,
  },
};

export function getEnemy(id) {
  return ENEMIES[id] || null;
}

export const BUDGET_CURVES = {
  tutorial: [40, 55, 70, 85, 100, 115, 130, 145],
  gentle: [50, 70, 90, 110, 130, 150, 170, 190, 210],
  moderate: [60, 85, 110, 140, 170, 200, 230, 260, 290, 320],
};
