export const ENEMIES = {
  logger: {
    id: "logger",
    name: "Logger",
    threatCost: 12,
    hp: 115,
    speed: 42,
    damage: 28,
    attackInterval: 0.95,
    manaBounty: 8,
    tags: ["crew", "ground", "choppable"],
    sprite: "logger-idle",
    width: 54,
    height: 68,
  },
  surveyor: {
    id: "surveyor",
    name: "Surveyor",
    threatCost: 14,
    hp: 95,
    speed: 48,
    damage: 18,
    attackInterval: 1.1,
    manaBounty: 10,
    tags: ["crew", "ground", "marks-targets"],
    sprite: "surveyor-idle",
    width: 50,
    height: 64,
  },
  "chainsaw-brute": {
    id: "chainsaw-brute",
    name: "Chainsaw Brute",
    threatCost: 22,
    hp: 200,
    speed: 30,
    damage: 45,
    attackInterval: 0.8,
    manaBounty: 14,
    tags: ["crew", "ground", "choppable", "heavy-chop"],
    sprite: "chainsaw-brute-idle",
    width: 62,
    height: 72,
  },
  bulldozer: {
    id: "bulldozer",
    name: "Bulldozer",
    threatCost: 28,
    hp: 260,
    speed: 24,
    damage: 52,
    attackInterval: 0.75,
    manaBounty: 15,
    tags: ["machine", "ground", "armored"],
    armor: 1,
    sprite: "bulldozer-idle",
    width: 78,
    height: 58,
  },
  "buzzsaw-drone": {
    id: "buzzsaw-drone",
    name: "Buzzsaw Drone",
    threatCost: 18,
    hp: 85,
    speed: 55,
    damage: 22,
    attackInterval: 1.0,
    manaBounty: 12,
    tags: ["machine", "flying"],
    flying: true,
    sprite: "buzzsaw-drone-idle",
    width: 48,
    height: 48,
  },
};

export function getEnemy(id) {
  return ENEMIES[id] || null;
}

export const BUDGET_CURVES = {
  tutorial: [40, 55, 70, 85, 100, 115, 130, 145],
  gentle: [50, 70, 90, 110, 130, 150, 170, 190, 210],
  moderate: [60, 85, 110, 140, 170, 200, 230, 260, 290, 320],
};
